/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <string.h>
#include "pins.h"
#include "uart.h"

#define RCC_IOPAEN     (1 << 2)
#define RCC_IOPBEN     (1 << 3)

void init_pins();
void UART2_ReceiveCallback(uint8_t data);

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

volatile uint32_t millis = 0;

void SysTick_Handler(void) {
    millis++;
}

void systick_init(void) {
    SysTick_Config(SystemCoreClock / 1000);  // 1 ms tick
}


int main(void){

	init_pins();
	for(;;);
}

void init_pins(){
	RCC_APB2ENR |= (RCC_IOPAEN | RCC_IOPBEN);

	// PB6 and PB7 (GPIOB_CRL — pins 0-7)
	GPIOB_CRL &= ~((0xF << (6 * 4)) | (0xF << (7 * 4))); // Clear bits
	GPIOB_CRL |=  ((0x3 << (6 * 4)) | (0x3 << (7 * 4))); // MODE=11 (50MHz), CNF=00 (Push-Pull)

	// PB8 and PB9 (GPIOB_CRH — pins 8-15)
	GPIOB_CRH &= ~((0xF << (0 * 4)) | (0xF << (1 * 4))); // Clear bits
	GPIOB_CRH |=  ((0x3 << (0 * 4)) | (0x3 << (1 * 4))); // MODE=11 (50MHz), CNF=00 (Push-Pull)
}

void UART2_StoreData(uint8_t data){
	char c = (char)data;

	if (c != '\n') {
		inputBuffer += c;
	}
}





